// Baby registry data. Edit freely: add, remove, or change items here.
// Prices were checked on 2026-10-01 and may change at the store.

var REGISTRY = {
  babyName: "Vyom Nepal",
  familyName: "The Nepal Family",
  dueDate: "2027-01-09",
  dueMonthLabel: "January 2027",
  contactEmail: "hellomuku@gmail.com",
  babylistUrl: "https://my.babylist.com/bini-bhattarai", // Babylist registry; the banner appears automatically
};

// Purchase-claim settings. Until these are filled in (see GOOGLE_SHEETS_SETUP.md),
// claims are saved in each visitor's own browser. Once connected, claims are shared
// with every visitor via the published sheet CSV.
var CLAIM_CONFIG = {
  formUrl: "",   // e.g. "https://docs.google.com/forms/d/e/XXXX/formResponse"
  entryIds: {
    itemId: "",  // Google Form entry id for the hidden item id
    name: "",    // entry id for buyer name
    platform: "",// entry id for store/platform
    order: "",   // entry id for order number (optional field)
    message: ""  // entry id for message to parents (optional field)
  },
  sheetCsvUrl: "" // published CSV link of the Form's response sheet
};

// Approximate size comparisons by gestational week (for the "watch him grow" section).
var WEEK_SIZES = [
  { week: 4,  size: "a poppy seed", emoji: "🌱", length: "about 2 mm", weight: "less than a gram" },
  { week: 5,  size: "a sesame seed", emoji: "🌾", length: "about 3 mm", weight: "less than a gram" },
  { week: 6,  size: "a lentil", emoji: "🫘", length: "about 6 mm", weight: "less than a gram" },
  { week: 7,  size: "a blueberry", emoji: "🫐", length: "about 1.3 cm", weight: "less than a gram" },
  { week: 8,  size: "a kidney bean", emoji: "🫘", length: "about 1.6 cm", weight: "about 1 g" },
  { week: 9,  size: "a cherry", emoji: "🍒", length: "about 2.3 cm", weight: "about 2 g" },
  { week: 10, size: "a kumquat", emoji: "🍊", length: "about 3.1 cm", weight: "about 4 g" },
  { week: 11, size: "a fig", emoji: "🫒", length: "about 4.1 cm", weight: "about 7 g" },
  { week: 12, size: "a lime", emoji: "🟢", length: "about 5.4 cm", weight: "about 14 g" },
  { week: 13, size: "a pea pod", emoji: "🫛", length: "about 7.4 cm", weight: "about 23 g" },
  { week: 14, size: "a lemon", emoji: "🍋", length: "about 8.7 cm", weight: "about 43 g" },
  { week: 15, size: "an apple", emoji: "🍎", length: "about 10 cm", weight: "about 70 g" },
  { week: 16, size: "an avocado", emoji: "🥑", length: "about 11.6 cm", weight: "about 100 g" },
  { week: 17, size: "a pear", emoji: "🍐", length: "about 13 cm", weight: "about 140 g" },
  { week: 18, size: "a bell pepper", emoji: "🫑", length: "about 14 cm", weight: "about 190 g" },
  { week: 19, size: "a tomato", emoji: "🍅", length: "about 15 cm", weight: "about 240 g" },
  { week: 20, size: "a banana", emoji: "🍌", length: "about 25.6 cm", weight: "about 300 g" },
  { week: 21, size: "a carrot", emoji: "🥕", length: "about 26.7 cm", weight: "about 350 g" },
  { week: 22, size: "a spaghetti squash", emoji: "🎃", length: "about 27.8 cm", weight: "about 430 g" },
  { week: 23, size: "a grapefruit", emoji: "🍊", length: "about 28.9 cm", weight: "about 500 g" },
  { week: 24, size: "an ear of corn", emoji: "🌽", length: "about 30 cm", weight: "about 600 g" },
  { week: 25, size: "a rutabaga", emoji: "🥔", length: "about 34.6 cm", weight: "about 660 g" },
  { week: 26, size: "a head of lettuce", emoji: "🥬", length: "about 35.6 cm", weight: "about 760 g" },
  { week: 27, size: "a cauliflower", emoji: "🥦", length: "about 36.6 cm", weight: "about 875 g" },
  { week: 28, size: "an eggplant", emoji: "🍆", length: "about 37.6 cm", weight: "about 1 kg" },
  { week: 29, size: "a butternut squash", emoji: "🎃", length: "about 38.6 cm", weight: "about 1.2 kg" },
  { week: 30, size: "a cabbage", emoji: "🥬", length: "about 39.9 cm", weight: "about 1.3 kg" },
  { week: 31, size: "a coconut", emoji: "🥥", length: "about 41 cm", weight: "about 1.5 kg" },
  { week: 32, size: "a jicama", emoji: "🥔", length: "about 42.4 cm", weight: "about 1.7 kg" },
  { week: 33, size: "a pineapple", emoji: "🍍", length: "about 43.7 cm", weight: "about 1.9 kg" },
  { week: 34, size: "a cantaloupe", emoji: "🍈", length: "about 45 cm", weight: "about 2.1 kg" },
  { week: 35, size: "a honeydew melon", emoji: "🍈", length: "about 46 cm", weight: "about 2.4 kg" },
  { week: 36, size: "a romaine heart", emoji: "🥬", length: "about 47.4 cm", weight: "about 2.6 kg" },
  { week: 37, size: "a bunch of Swiss chard", emoji: "🥬", length: "about 48.6 cm", weight: "about 2.9 kg" },
  { week: 38, size: "a pumpkin", emoji: "🎃", length: "about 49.5 cm", weight: "about 3.1 kg" },
  { week: 39, size: "a watermelon", emoji: "🍉", length: "about 50.7 cm", weight: "about 3.3 kg" },
  { week: 40, size: "a watermelon", emoji: "🍉", length: "about 51 cm", weight: "about 3.5 kg" },
  { week: 41, size: "a watermelon", emoji: "🍉", length: "about 51.7 cm", weight: "about 3.6 kg" },
  { week: 42, size: "a watermelon", emoji: "🍉", length: "about 52 cm", weight: "about 3.7 kg" }
];

var ITEMS = [
  {
    id: "bravo-trio",
    name: "Chicco - Bravo Trio Travel System Camden",
    brand: "Chicco",
    category: "Travel",
    priority: "must", // "must" or "nice"
    price: "$489.99",
    store: "MacroBaby",
    url: "https://www.macrobaby.com/products/chicco-bravo-trio-travel-system-camden?variant=39714051719227",
    img: "assets/img/bravo-trio.jpg",
    blurb: "Our pick for the one-and-done travel system: stroller plus the KeyFit 30 infant seat, with a one-hand quick fold for the car.",
  },
  {
    id: "ergobaby-omni",
    name: "Ergobaby(TM) Omni Classic Baby Carrier, Mesh, Gray",
    brand: "Pottery Barn Kids",
    category: "Travel",
    priority: "nice", // "must" or "nice"
    price: "$179",
    store: "Pottery Barn Kids",
    url: "https://www.potterybarnkids.com/products/ergobaby-360-omni-carrier/?catalogId=10&sku=8934615&cm_ven=organicsocial&cm_cat=InstagramFacebook&cm_pla=shoppable&cm_ite=skuname%2F",
    img: "assets/img/ergobaby-omni.jpg",
    blurb: "Keeps baby close on walks and errands, with lumbar support for longer carries.",
  },
  {
    id: "hatch-rest",
    name: "Hatch Rest + 2nd Gen Sound Machine & Nightlight with Battery",
    brand: null,
    category: "Nursery",
    priority: "nice", // "must" or "nice"
    price: "$99.99",
    store: "Name Dropper Kids",
    url: "https://namedropperkids.com/products/hatch-rest-2nd-gen-sound-machine-nightlight-with-battery?variant=46142805573875",
    img: "assets/img/hatch-rest.jpg",
    blurb: "White noise, night light, and wake-up cues in one, controlled from a phone.",
  },
  {
    id: "swaddles",
    name: "aden + anais essentials 4pk Cotton Muslin Swaddle Blankets - Sage Woodland",
    brand: "aden + anais essentials",
    category: "Nursery",
    priority: "must", // "must" or "nice"
    price: "$39.99",
    store: "Target",
    url: "https://www.target.com/p/aden-by-aden-anais-essentials-muslin-swaddle-blankets-woodland-4pk/-/A-92407763",
    img: "assets/img/swaddles.jpg",
    blurb: "Soft, breathable muslin blankets for swaddling, burping, and everything in between.",
  },
  {
    id: "boppy",
    name: "Boppy Nursing Pillow in Green Animal Sketches | 100% Polyester",
    brand: "Boppy",
    category: "Feeding",
    priority: "must", // "must" or "nice"
    price: "$49.99",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/boppy-nursing-pillow/70620/2351358?reg_item_id=893744916&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/boppy.jpg",
    blurb: "The classic nursing pillow: supportive positioning for feeding time.",
  },
  {
    id: "avent-bottles",
    name: "Philips Avent Natural Baby Bottle Newborn Starter Gift Set",
    brand: "Philips AVENT",
    category: "Feeding",
    priority: "must", // "must" or "nice"
    price: "$48.19",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/philips-avent-natural-baby-bottle-newborn-starter-gift-set/24134/1006494?reg_item_id=893744974&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/avent-bottles.jpg",
    blurb: "Newborn starter set with anti-colic nipples, easy to clean and assemble.",
  },
  {
    id: "avent-nipples",
    name: "Philips Avent Natural Response Nipples, Flow 1 (4-Pack)",
    brand: "Philips AVENT",
    category: "Feeding",
    priority: "nice", // "must" or "nice"
    price: "$13.26",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/philips-avent-natural-response-nipples-4-pack/75193/2565045?reg_item_id=883524584&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/avent-nipples.jpg",
    blurb: "Extra-slow-flow replacement nipples for the newborn bottles, for paced, breast-like feeding.",
  },
  {
    id: "graco-highchair",
    name: "Ready2Dine\u00ae 4-in-1 Highchair",
    brand: "Graco",
    category: "Feeding",
    priority: "nice", // "must" or "nice"
    price: "$99.99",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/graco-ready2dine-dlx-highchair/80440/2902996?reg_item_id=893745201&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/graco-highchair.jpg",
    blurb: "Grows from infant recline to toddler booster, one chair for every stage.",
  },
  {
    id: "ubbi-pail",
    name: "Ubbi Stainless Steel Diaper Pail - Grey",
    brand: "Ubbi",
    category: "Diapering",
    priority: "must", // "must" or "nice"
    price: "$79.99",
    store: "Albee Baby",
    url: "https://www.albeebaby.com/products/ubbi-diaper-pail-grey?variant=49935523315943",
    img: "assets/img/ubbi-pail.jpg",
    blurb: "Steel body locks in odors and uses regular trash bags, no pricey refills.",
  },
  {
    id: "keekaroo",
    name: "Keekaroo Peanut Changer",
    brand: "Keekaroo",
    category: "Diapering",
    priority: "nice", // "must" or "nice"
    price: "$149.95",
    store: "Babinski's",
    url: "https://babinskis.com/products/keekaroo-peanut-changer?variant=40962353594429",
    img: "assets/img/keekaroo.jpg",
    blurb: "Waterproof, wipeable changer, no extra covers or laundry needed.",
  },
  {
    id: "fp-tub",
    name: "Fisher-Price 4-in-1 Sling 'n Seat Tub | by Fleet Farm",
    brand: "Fisher-Price",
    category: "Bath & Health",
    priority: "must", // "must" or "nice"
    price: "$29.10",
    store: "Fleet Farm",
    url: "https://www.fleetfarm.com/detail/fisher-price-4-in-1-sling-n-seat-tub/0000101801891?Ntt=101801891",
    img: "assets/img/fp-tub.jpg",
    blurb: "Four stages from newborn sling to toddler tub in one compact footprint.",
  },
  {
    id: "burts-towels",
    name: "Burt's Bees Baby Organic Hooded Towels (2-Pack) in Little Ducks",
    brand: "Burt's Bees Baby",
    category: "Bath & Health",
    priority: "nice", // "must" or "nice"
    price: "$29.95",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/burt-s-bees-baby-organic-hooded-towels-2-pack/14450/230642?reg_item_id=893745886&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/burts-towels.jpg",
    blurb: "Organic cotton hooded towels, soft and absorbent after bath time.",
  },
  {
    id: "frida-thermometer",
    name: "Frida Baby 3-in-1 Ear and Forehead Infrared Thermometer",
    brand: "Frida",
    category: "Bath & Health",
    priority: "must", // "must" or "nice"
    price: "$31.99",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/fridababy-3-in-1-ear-forehead-touchless-infrared-thermometer/41460/1601646?reg_item_id=893746030&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/frida-thermometer.jpg",
    blurb: "Quick ear, forehead, and touchless readings for middle-of-the-night checks.",
  },
  {
    id: "carters-onesies",
    name: "Carter's Baby Unisex 5-Pack Bodysuits",
    brand: "Carter's",
    category: "Clothing",
    priority: "must", // "must" or "nice"
    price: "$24.99",
    store: "CookiesKids",
    url: "https://www.cookieskids.com/Product.aspx?l=00170062006102200000&p=CTR07100&c=WHI&s=0006M&a=FacebookFeed",
    img: "assets/img/carters-onesies.jpg",
    blurb: "Everyday bodysuits in soft cotton, the unofficial newborn uniform.",
  },
  {
    id: "fp-gym",
    name: "Fisher Price - Glow & Grow Kick & Play Gym, Blue",
    brand: null,
    category: "Play",
    priority: "nice", // "must" or "nice"
    price: "$59.99",
    store: "MacroBaby",
    url: "https://www.macrobaby.com/products/fisher-price-glow-grow-kick-play-gym-blue?variant=43094643867707",
    img: "assets/img/fp-gym.jpg",
    blurb: "Kick-and-play piano gym for tummy time, batting practice, and first music lessons.",
  },
  {
    id: "bed-rail",
    name: "Regalo Swing down Bed Guard Rail XL - White",
    brand: "Regalo",
    category: "Nursery",
    priority: "must", // "must" or "nice"
    price: "$34.99",
    store: "Target",
    url: "https://www.target.com/p/regalo-swing-down-bed-guard-rail-xl-white/-/A-94919917",
    img: "assets/img/bed-rail.jpg",
    blurb: "Extra-long swing-down rail for the bed, so Vyom can sleep safely right beside us.",
  },
  {
    id: "nursing-glider",
    name: "daVinci Piper Recliner and Swivel Glider - Pine Green",
    brand: "DaVinci",
    category: "Nursery",
    priority: "must", // "must" or "nice"
    price: "$349",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/davinci-piper-recliner/15778/1935951?reg_item_id=893746484&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/nursing-glider.jpg",
    blurb: "A proper reclining glider for late-night feeds, with smooth swivel and lumbar support.",
  },
  {
    id: "video-monitor",
    name: "Infant Optics Digital Video Monitor DXR-8 Pro",
    brand: "Infant Optics",
    category: "Nursery",
    priority: "must", // "must" or "nice"
    price: "$199.99",
    store: "Target",
    url: "https://www.target.com/p/infant-optics-digital-video-monitor-dxr-8-pro/-/A-80641472",
    img: "assets/img/video-monitor.jpg",
    blurb: "A dedicated video monitor with a 5-inch screen, no WiFi or app needed.",
  },
  {
    id: "big-playpen",
    name: "SKYSHALO Extra Large Baby Playpen, 78.7 x 70.3 in.",
    brand: "SKYSHALO",
    category: "Play",
    priority: "nice", // "must" or "nice"
    price: "$65.99",
    store: "Home Depot",
    url: "https://www.homedepot.com/p/SKYSHALO-Baby-Playpen-78-7-x-70-3-in-Extra-Large-Playpen-for-Babies-Toddlers-Indoor-Outdoor-Baby-Fence-Play-Yard-YYEWSHLBYYEWGT104001V0-250915/338697786",
    img: "assets/img/big-playpen.jpg",
    blurb: "Extra-large foldable play yard, roomy enough for Vyom to crawl around and for a parent to climb in too.",
  },
  {
    id: "bottle-washer",
    name: "Momcozy KleanPal Pro Baby Bottle Washer and Sterilizer in Sage",
    brand: "Momcozy",
    category: "Feeding",
    priority: "nice", // "must" or "nice"
    price: "$299.99",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/momcozy-kleanpal-pro-baby-bottle-washer-and-sterilizer-1730408600/66759/2233069?reg_item_id=893746806&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/bottle-washer.jpg",
    blurb: "Washes, sterilizes, and dries bottles and pump parts in one go, a real time saver.",
  },
  {
    id: "washer-detergent",
    name: "Washing Block for KleanPal Pro Bottle Washer, 120 Tablets",
    brand: "Momcozy",
    category: "Feeding",
    priority: "must", // "must" or "nice"
    price: "$19.99",
    store: "Momcozy",
    url: "https://momcozy.com/products/washing-block-for-kleanpal-pro-bottle-washer-120-tablets?variant=44586759880902",
    img: "assets/img/washer-detergent.jpg",
    blurb: "The matching cleaning tablets that keep the bottle washer running.",
  },
  {
    id: "sudocrem",
    name: "Sudocrem Antiseptic Healing Cream 250g",
    brand: "Sudocrem",
    category: "Diapering",
    priority: "must", // "must" or "nice"
    price: "$18.99",
    store: "Taste of Britain",
    url: "https://www.tasteofbritain.com/products/sudocrem-250g?variant=40455298449463",
    img: "assets/img/sudocrem.jpg",
    blurb: "Your pick over Desitin: the classic antiseptic healing cream for diaper rash and irritated skin.",
  },
  {
    id: "nosefrida-kit",
    name: "NoseFrida Nasal Aspirator Saline Kit",
    brand: null,
    category: "Bath & Health",
    priority: "must", // "must" or "nice"
    price: "$20.99",
    store: "Crib & Kids",
    url: "https://cribandkids.com/products/fridababy-nosefrida-saline-kit?variant=31833033834582",
    img: "assets/img/nosefrida-kit.jpg",
    blurb: "Clears tiny congested noses fast, with saline spray included.",
  },
  {
    id: "diaper-bag",
    name: "Skip Hop Forma Backpack Diaper Bag - Navy",
    brand: "Skip Hop",
    category: "Travel",
    priority: "must", // "must" or "nice"
    price: "$79",
    store: "Carter's",
    url: "https://www.carters.com/p/forma-backpack-diaper-bag-navy/194133669187",
    img: "assets/img/diaper-bag.jpg",
    blurb: "A backpack-style bag that fits bottles, diapers, and a change of clothes.",
  },
  {
    id: "milk-bags",
    name: "Lansinoh - Milk Storage Bag, 25Ct",
    brand: "Lansinoh",
    category: "Feeding",
    priority: "nice", // "must" or "nice"
    price: "$8.99",
    store: "MacroBaby",
    url: "https://www.macrobaby.com/products/lansinoh-milk-storage-bags-25-count?variant=39711940608059",
    img: "assets/img/milk-bags.jpg",
    blurb: "Leak-proof bags for pumped milk, a perfect partner to the Spectra pump.",
  },
  {
    id: "humidifier",
    name: "MistAire\u2122 Studio Ultrasonic Cool Mist Humidifier",
    brand: "Pure Enrichment",
    category: "Nursery",
    priority: "nice", // "must" or "nice"
    price: "$32.99",
    store: "Pure Enrichment",
    url: "https://pureenrichment.com/products/mistaire-studio-ultrasonic-cool-mist-humidifier-for-small-rooms?variant=14891559944244",
    img: "assets/img/humidifier.jpg",
    blurb: "Gentle cool mist for dry winter air, quiet enough for the nursery.",
  },
  {
    id: "car-mirror",
    name: "Back Seat Baby Car Mirror Ladybug",
    brand: null,
    category: "Travel",
    priority: "nice", // "must" or "nice"
    price: "$19.99",
    store: "LulyBoo",
    url: "https://lulyboo.com/products/back-seat-baby-car-mirror-ladybug?variant=49905080664301",
    img: "assets/img/car-mirror.jpg",
    blurb: "Lets the driver see Vyom in his rear-facing seat at a glance.",
  },
  {
    id: "halo-sleepsack",
    name: "Halo SleepSack Swaddle Cotton in Forest Friends Size Newborn | 100% Cotton",
    brand: "HALO",
    category: "Nursery",
    priority: "must", // "must" or "nice"
    price: "$34.95",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/halo-sleepsack-swaddle-cotton/2204/1699370?reg_item_id=893747806&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/halo-sleepsack.jpg",
    blurb: "A wearable blanket that keeps Vyom snug and safe without loose blankets in the bed.",
  },
  {
    id: "lanolin",
    name: "Lansinoh Lanolin Nipple Ointment",
    brand: null,
    category: "Feeding",
    priority: "nice", // "must" or "nice"
    price: "$10.99",
    store: "Simply Birth",
    url: "https://simplybirth.com/products/lansinoh-nipple-lanolin?variant=1238136956",
    img: "assets/img/lanolin.jpg",
    blurb: "Soothes and protects sore nipples in the early breastfeeding days.",
  },
  {
    id: "giftcard-amazon",
    name: "Amazon Gift Card",
    brand: null,
    category: "Gift Cards",
    priority: "nice", // "must" or "nice"
    price: "Any amount",
    store: "Amazon",
    url: "https://www.amazon.com/gift-cards/",
    giftCard: true,
    blurb: "Any amount from $5 up, delivered by email. Lets us pick exactly what Vyom needs, when he needs it.",
  },
  {
    id: "giftcard-target",
    name: "Target Gift Card",
    brand: null,
    category: "Gift Cards",
    priority: "nice", // "must" or "nice"
    price: "Any amount",
    store: "Target",
    url: "https://www.target.com/c/gift-cards/-/N-5xsxu?type=products",
    giftCard: true,
    blurb: "Any amount from $5 up. Perfect for diapers, wipes, and all the little things that add up.",
  },
  {
    id: "giftcard-costco",
    name: "Costco Shop Card",
    brand: null,
    category: "Gift Cards",
    priority: "nice", // "must" or "nice"
    price: "Any amount",
    store: "Costco",
    url: "https://www.costco.com/CatalogSearch?dept=All&keyword=costco+shop+card",
    giftCard: true,
    blurb: "From $25 up, and it works in the warehouse even without a membership. Perfect for stocking up on diapers and wipes in bulk.",
  },
  {
    id: "newton-bassinet",
    name: "Newton Baby Bassinet & Bedside Sleeper - Grey",
    brand: "Newton Baby",
    category: "Nursery",
    priority: "must", // "must" or "nice"
    price: "$299.99",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/newton-baby-bassinet-bedside-sleeper/38523/1502903?reg_item_id=883526061&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/newton-bassinet.jpg",
    blurb: "A breathable bedside sleeper that keeps Vyom close through the night, right beside our bed.",
  },
  {
    id: "brezza-washer",
    name: "Baby Brezza Bottle Washer Pro - Charcoal",
    brand: "Baby Brezza",
    category: "Feeding",
    priority: "nice", // "must" or "nice"
    price: "$299.99",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/baby-brezza-bottle-washer-pro/44961/2200478?reg_item_id=883525167&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/brezza-washer.jpg",
    blurb: "Automatically washes, sterilizes, and dries bottles at the push of a button.",
  },
  {
    id: "drbrowns-set",
    name: "Dr. Brown's Options+ Narrow Bottles + Happy Paci Set (3-Pack)",
    brand: "Dr. Brown's",
    category: "Feeding",
    priority: "nice", // "must" or "nice"
    price: "$19.99",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/dr-brown-s-options-narrow-anti-colic-baby-bottles-happy-paci-set-3-pack/85136/3481666?reg_item_id=883523832&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/drbrowns-set.jpg",
    blurb: "Anti-colic narrow bottles plus a Happy Paci set, sized for newborn feeds.",
  },
  {
    id: "avent-bottles-4oz",
    name: "Philips Avent Natural Baby Bottles 4oz, Blue (4-Pack)",
    brand: "Philips AVENT",
    category: "Feeding",
    priority: "nice", // "must" or "nice"
    price: "$26.12",
    store: "Babylist",
    url: "https://www.babylist.com/ggp/philips-avent-natural-baby-bottle-with-natural-response-nipple/24594/2085106?reg_item_id=883522851&registry_id=15025577&registry_uuid=FC87C487-D435-49DA-B2AA-368E40258CF2",
    img: "assets/img/avent-bottles-4oz.jpg",
    blurb: "Four 4oz Natural Response bottles in blue, sized just right for the early weeks.",
  },
  {
    id: "giftcard-babylist",
    name: "Babylist Gift Card",
    brand: null,
    category: "Gift Cards",
    priority: "nice", // "must" or "nice"
    price: "Any amount",
    store: "Babylist",
    url: "https://my.babylist.com/bini-bhattarai",
    giftCard: true,
    blurb: "A Babylist gift card from $25 up, spendable across the whole registry.",
  },
];
